# Generated by Django 3.2.4 on 2021-08-27 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('ngay_sinh', models.CharField(max_length=10)),
                ('que_quan', models.CharField(max_length=500)),
                ('ho_khau', models.CharField(max_length=500)),
                ('sdt', models.CharField(max_length=10)),
                ('trinh_do_hoc_van', models.CharField(max_length=10)),
                ('cap_bac', models.CharField(max_length=20)),
                ('chuc_vu', models.CharField(max_length=20)),
                ('ngay_vao_nganh', models.CharField(default='1/1/2021', max_length=10)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
