# Generated by Django 3.2.4 on 2021-08-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='slogan',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
