# Generated by Django 3.2.4 on 2022-01-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20211003_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='team',
            field=models.ManyToManyField(blank=True, null=True, to='profiles.Team'),
        ),
    ]
