# Generated by Django 3.2.4 on 2022-01-11 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_userprofile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='member',
        ),
    ]
