# Generated by Django 3.2.4 on 2022-05-19 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qlpt', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Thu_nghiem',
            new_name='Danh_muc_phuong_tien',
        ),
    ]
