# Generated by Django 3.2.4 on 2022-05-19 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qlpt', '0002_rename_thu_nghiem_danh_muc_phuong_tien'),
    ]

    operations = [
        migrations.RenameField(
            model_name='danh_muc_phuong_tien',
            old_name='chat_luong',
            new_name='ten',
        ),
        migrations.CreateModel(
            name='Chung_loai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stt', models.IntegerField(blank=True, null=True)),
                ('ten', models.CharField(max_length=200, null=True)),
                ('mo_ta', models.CharField(blank=True, max_length=500, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='qlpt.chung_loai')),
            ],
            options={
                'ordering': ['stt'],
            },
        ),
        migrations.AddField(
            model_name='danh_muc_phuong_tien',
            name='chung_loai',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='qlpt.chung_loai'),
            preserve_default=False,
        ),
    ]
