# Generated by Django 3.2.4 on 2022-05-19 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qlpt', '0003_auto_20220519_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danh_muc_phuong_tien',
            name='chung_loai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='qlpt.chung_loai'),
        ),
        migrations.AlterField(
            model_name='danh_muc_phuong_tien',
            name='ten',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
