# Generated by Django 3.2.4 on 2022-05-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlpt', '0004_auto_20220519_0758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chung_loai',
            options={'ordering': ['maso']},
        ),
        migrations.RemoveField(
            model_name='chung_loai',
            name='stt',
        ),
        migrations.AddField(
            model_name='chung_loai',
            name='maso',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
