# Generated by Django 3.2.4 on 2022-05-21 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qlpt', '0005_auto_20220519_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Danh_muc_kho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phuong_tien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200)),
                ('don_vi_tinh', models.CharField(max_length=200)),
                ('danh_muc_kho', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='qlpt.danh_muc_kho')),
                ('danh_muc_phuong_tien', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='qlpt.danh_muc_phuong_tien')),
            ],
        ),
        migrations.CreateModel(
            name='Phieu_xuat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian', models.CharField(blank=True, max_length=10, null=True)),
                ('ben_giao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ben_giao', to='qlpt.danh_muc_kho')),
                ('ben_nhan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ben_nhan', to='qlpt.danh_muc_kho')),
            ],
        ),
        migrations.CreateModel(
            name='Chi_tiet_phieu_xuat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
                ('phieu_xuat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlpt.phieu_xuat')),
                ('phuong_tien', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='qlpt.phuong_tien')),
            ],
        ),
    ]
