# Generated by Django 3.2.4 on 2022-05-22 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qlpt', '0006_chi_tiet_phieu_xuat_danh_muc_kho_phieu_xuat_phuong_tien'),
    ]

    operations = [
        migrations.CreateModel(
            name='Danh_muc_nguon_cap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200)),
                ('mo_ta', models.CharField(blank=True, max_length=500, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='phieu_xuat',
            name='success',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Phieu_nhap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian', models.CharField(blank=True, max_length=10, null=True)),
                ('success', models.BooleanField(default=False)),
                ('kho_nhap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='qlpt.danh_muc_kho')),
                ('nguon_cap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='qlpt.danh_muc_nguon_cap')),
            ],
        ),
        migrations.CreateModel(
            name='Chi_tiet_phieu_nhap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
                ('phieu_nhap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlpt.phieu_nhap')),
                ('phuong_tien', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='qlpt.phuong_tien')),
            ],
        ),
    ]
