# Generated by Django 3.2.4 on 2022-05-22 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qlpt', '0007_auto_20220522_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chi_tiet_phieu_nhap',
            name='phuong_tien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='nhap', to='qlpt.danh_muc_phuong_tien'),
        ),
    ]
