# Generated by Django 3.2.4 on 2022-06-02 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qlpt', '0008_alter_chi_tiet_phieu_nhap_phuong_tien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chi_tiet_phieu_nhap',
            name='phieu_nhap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlpt.phieu_nhap', verbose_name='Phiếu nhập'),
        ),
        migrations.AlterField(
            model_name='chi_tiet_phieu_nhap',
            name='phuong_tien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='qlpt.danh_muc_phuong_tien', verbose_name='Phương tiện'),
        ),
        migrations.AlterField(
            model_name='chi_tiet_phieu_nhap',
            name='so_luong',
            field=models.IntegerField(verbose_name='Số lượng'),
        ),
        migrations.AlterField(
            model_name='chi_tiet_phieu_xuat',
            name='phuong_tien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='qlpt.danh_muc_phuong_tien'),
        ),
        migrations.AlterField(
            model_name='chung_loai',
            name='maso',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Mã số'),
        ),
        migrations.AlterField(
            model_name='chung_loai',
            name='mo_ta',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='chung_loai',
            name='ten',
            field=models.CharField(max_length=200, null=True, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='phieu_nhap',
            name='kho_nhap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='qlpt.danh_muc_kho', verbose_name='Kho nhập'),
        ),
        migrations.AlterField(
            model_name='phieu_nhap',
            name='nguon_cap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='qlpt.danh_muc_nguon_cap', verbose_name='Nguồn cấp'),
        ),
        migrations.AlterField(
            model_name='phieu_nhap',
            name='thoi_gian',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Thời gian nhập'),
        ),
        migrations.DeleteModel(
            name='Phuong_tien',
        ),
    ]
