# Generated by Django 3.2.4 on 2022-06-02 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qlpt', '0009_auto_20220602_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chi_tiet_phieu_nhap',
            options={'verbose_name': 'Chi tiết phiếu nhập', 'verbose_name_plural': 'Chi tiết phiếu nhập'},
        ),
        migrations.AlterModelOptions(
            name='chi_tiet_phieu_xuat',
            options={'verbose_name': 'Chi tiết phiếu xuất', 'verbose_name_plural': 'Chi tiết phiếu xuất'},
        ),
        migrations.AlterModelOptions(
            name='chung_loai',
            options={'ordering': ['maso'], 'verbose_name': 'Chủng loại', 'verbose_name_plural': 'Chủng loại'},
        ),
        migrations.AlterModelOptions(
            name='danh_muc_kho',
            options={'verbose_name': 'Danh mục kho', 'verbose_name_plural': 'Danh mục kho'},
        ),
        migrations.AlterModelOptions(
            name='danh_muc_nguon_cap',
            options={'verbose_name': 'Danh mục nguồn cấp', 'verbose_name_plural': 'Danh mục nguồn cấp'},
        ),
        migrations.AlterModelOptions(
            name='danh_muc_phuong_tien',
            options={'verbose_name': 'Danh mục phương tiện', 'verbose_name_plural': 'Danh mục phương tiện'},
        ),
        migrations.AlterModelOptions(
            name='phieu_nhap',
            options={'verbose_name': 'Phiếu nhập', 'verbose_name_plural': 'Phiếu nhập'},
        ),
        migrations.AlterModelOptions(
            name='phieu_xuat',
            options={'verbose_name': 'Phiếu xuất', 'verbose_name_plural': 'Phiếu xuất'},
        ),
        migrations.RenameField(
            model_name='phieu_xuat',
            old_name='ben_nhan',
            new_name='kho_nhap',
        ),
        migrations.RenameField(
            model_name='phieu_xuat',
            old_name='ben_giao',
            new_name='kho_xuat',
        ),
    ]
