# Generated by Django 3.2.4 on 2022-06-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlpt', '0010_auto_20220602_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='danh_muc_kho',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
