# Generated by Django 3.2.4 on 2022-06-07 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qlpt', '0011_danh_muc_kho_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='danh_muc_phuong_tien',
            options={'ordering': ['chung_loai'], 'verbose_name': 'Danh mục phương tiện', 'verbose_name_plural': 'Danh mục phương tiện'},
        ),
        migrations.AlterModelOptions(
            name='phieu_nhap',
            options={'ordering': ['-thoi_gian'], 'verbose_name': 'Phiếu nhập', 'verbose_name_plural': 'Phiếu nhập'},
        ),
        migrations.AlterField(
            model_name='chung_loai',
            name='ten',
            field=models.CharField(max_length=500, null=True, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='phieu_nhap',
            name='kho_nhap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='qlpt.danh_muc_kho', verbose_name='Kho nhập'),
        ),
        migrations.AlterField(
            model_name='phieu_nhap',
            name='thoi_gian',
            field=models.CharField(max_length=10, verbose_name='Thời gian nhập'),
        ),
    ]
