# Generated by Django 3.2.4 on 2022-06-07 09:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qlpt', '0012_auto_20220607_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='danh_muc_phuong_tien',
            options={'ordering': ['chung_loai__maso'], 'verbose_name': 'Danh mục phương tiện', 'verbose_name_plural': 'Danh mục phương tiện'},
        ),
        migrations.AddField(
            model_name='chi_tiet_phieu_nhap',
            name='nam_cap',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Năm cấp'),
        ),
        migrations.AddField(
            model_name='chi_tiet_phieu_nhap',
            name='nguon_cap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='qlpt.danh_muc_nguon_cap', verbose_name='Nguồn cấp'),
        ),
        migrations.AddField(
            model_name='chi_tiet_phieu_nhap',
            name='nguyen_gia',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nguyên giá (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='phieu_nhap',
            name='kho_nhap',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='qlpt.danh_muc_kho', verbose_name='Kho nhập'),
        ),
        migrations.AlterField(
            model_name='phieu_nhap',
            name='thoi_gian',
            field=models.CharField(default='', max_length=10, verbose_name='Thời gian nhập'),
        ),
    ]
