# Generated by Django 3.2.4 on 2022-07-27 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qlpt', '0015_sua_chua'),
    ]

    operations = [
        migrations.AddField(
            model_name='phieu_nhap',
            name='kho_xuat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='giao', to='qlpt.danh_muc_kho', verbose_name='Kho xuất'),
        ),
        migrations.AlterField(
            model_name='phieu_nhap',
            name='kho_nhap',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='nhan', to='qlpt.danh_muc_kho', verbose_name='Kho nhập'),
        ),
    ]
