# Generated by Django 3.2.4 on 2022-08-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlpt', '0016_auto_20220727_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phieu_xuat',
            name='kho_nhap',
        ),
        migrations.RemoveField(
            model_name='phieu_xuat',
            name='kho_xuat',
        ),
        migrations.AddField(
            model_name='danh_muc_phuong_tien',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='static'),
        ),
        migrations.DeleteModel(
            name='Chi_tiet_phieu_xuat',
        ),
        migrations.DeleteModel(
            name='Phieu_xuat',
        ),
    ]
