# Generated by Django 3.2.4 on 2022-08-16 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qlpt', '0017_auto_20220816_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='danh_muc_phuong_tien',
            old_name='file',
            new_name='hinh_anh',
        ),
    ]
