# Generated by Django 3.2.4 on 2022-08-16 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qlpt', '0018_rename_file_danh_muc_phuong_tien_hinh_anh'),
    ]

    operations = [
        migrations.AddField(
            model_name='danh_muc_phuong_tien',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='static', verbose_name='File liên quan'),
        ),
        migrations.AlterField(
            model_name='danh_muc_phuong_tien',
            name='chung_loai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='qlpt.chung_loai', verbose_name='Chủng loại'),
        ),
        migrations.AlterField(
            model_name='danh_muc_phuong_tien',
            name='hinh_anh',
            field=models.FileField(blank=True, null=True, upload_to='static', verbose_name='Hình ảnh'),
        ),
        migrations.AlterField(
            model_name='danh_muc_phuong_tien',
            name='ten',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tên'),
        ),
    ]
