# Generated by Django 3.2.4 on 2022-08-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlpt', '0019_auto_20220816_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='phieu_nhap',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
