# Generated by Django 3.2.4 on 2022-09-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlpt', '0020_phieu_nhap_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='phieu_nhap',
            name='quyetdinh',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
