# Generated by Django 3.2.4 on 2022-10-27 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qlpt', '0021_phieu_nhap_quyetdinh'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoQuanLy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bienSo', models.CharField(max_length=12, verbose_name='Biển số')),
                ('soKhung', models.CharField(max_length=30, verbose_name='Số khung')),
                ('soMay', models.CharField(max_length=30, verbose_name='Số máy')),
                ('soDongCo', models.CharField(max_length=30, verbose_name='Số động cơ')),
                ('serial', models.CharField(max_length=100, verbose_name='Biển số/Số máy/Số động cơ/...')),
                ('phuongTien', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='qlpt.danh_muc_phuong_tien', verbose_name='Phương tiện')),
            ],
        ),
    ]
