# Generated by Django 3.2.4 on 2021-07-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
