# Generated by Django 3.2.4 on 2022-01-20 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_alter_doc_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='body',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='description',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='ten',
        ),
        migrations.AddField(
            model_name='doc',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='doc',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doc',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doc',
            name='text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('file', models.FileField(blank=True, null=True, upload_to='static')),
                ('Doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.doc')),
            ],
        ),
    ]
