# Generated by Django 3.2.4 on 2022-01-20 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_auto_20220120_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='file',
            field=models.FileField(upload_to='static'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
