# Generated by Django 3.2.4 on 2021-07-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phuong_tien',
            name='bien_so',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
