# Generated by Django 3.2.4 on 2021-07-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PT', '0002_phuong_tien_bien_so'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phuong_tien',
            name='bien_so',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
