# Generated by Django 3.2.4 on 2021-07-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PT', '0004_alter_phuong_tien_thoi_gian_san_xuat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phuong_tien',
            name='thoi_gian_dua_vao_hoat_dong',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='phuong_tien',
            name='thoi_gian_nhan',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='phuong_tien',
            name='thoi_gian_san_xuat',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
