# Generated by Django 3.2.4 on 2021-07-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PT', '0005_auto_20210712_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phuong_tien',
            name='thoi_gian_dua_vao_hoat_dong',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='phuong_tien',
            name='thoi_gian_nhan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='phuong_tien',
            name='thoi_gian_san_xuat',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
