# Generated by Django 3.2.4 on 2021-07-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PT', '0006_auto_20210712_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='phuong_tien',
            name='so_dong_co',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
