# Generated by Django 3.2.4 on 2021-08-01 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PT', '0008_dinh_muc_nhien_lieu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nhat_trinh_xe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_luc_ve', models.IntegerField(null=True)),
                ('noi_dung_cong_tac', models.CharField(blank=True, max_length=200, null=True)),
                ('noi_den_cong_tac', models.CharField(blank=True, max_length=200, null=True)),
                ('phuong_tien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PT.phuong_tien')),
            ],
        ),
    ]
