# Generated by Django 3.2.4 on 2021-08-01 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PT', '0009_nhat_trinh_xe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nhat_trinh_xe',
        ),
    ]
