# Generated by Django 3.2.4 on 2021-08-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PT', '0011_nhat_trinh_xe'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhat_trinh_xe',
            name='thoi_gian',
            field=models.DateTimeField(null=True),
        ),
    ]
