# Generated by Django 3.2.4 on 2021-08-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PT', '0013_alter_nhat_trinh_xe_thoi_gian'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhat_trinh_xe',
            name='km_luc_di',
            field=models.IntegerField(null=True),
        ),
    ]
