# Generated by Django 3.2.4 on 2021-08-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PT', '0014_nhat_trinh_xe_km_luc_di'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phuong_tien',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to='frontend/build/static/images/upload/'),
        ),
    ]
