# Generated by Django 3.2.4 on 2021-08-14 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PT', '0015_alter_phuong_tien_hinh_anh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phuong_tien',
            name='chung_loai',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.RESTRICT, related_name='phuongtien_list', to='PT.chung_loai'),
        ),
    ]
