# Generated by Django 3.2.4 on 2021-08-21 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PT', '0016_alter_phuong_tien_chung_loai'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phuong_tien',
            options={'ordering': ['-order']},
        ),
        migrations.AddField(
            model_name='phuong_tien',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
