# Generated by Django 3.2.4 on 2021-08-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PT', '0017_auto_20210821_1114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chung_loai',
            options={'ordering': ['stt']},
        ),
        migrations.AddField(
            model_name='chung_loai',
            name='stt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
