# Generated by Django 3.2.4 on 2022-01-10 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PT', '0021_remove_phuong_tien_nguoi_quan_ly'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='static/images/upload/')),
                ('phuong_tien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PT.phuong_tien')),
            ],
        ),
        migrations.DeleteModel(
            name='To',
        ),
    ]
