# Generated by Django 3.2.4 on 2022-01-10 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PT', '0022_auto_20220110_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phuong_tien',
            name='hinh_anh',
        ),
    ]
