# Generated by Django 3.2.4 on 2021-10-29 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diaban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200)),
                ('mota', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200)),
                ('dia_chi', models.CharField(max_length=500)),
                ('sdt', models.CharField(blank=True, max_length=11, null=True)),
                ('co_quan_quan_ly', models.CharField(blank=True, max_length=200, null=True)),
                ('sdt_co_quan_quan_ly', models.CharField(blank=True, max_length=11, null=True)),
                ('loai_hinh_co_so', models.CharField(blank=True, max_length=50, null=True)),
                ('dia_ban', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='coso.diaban')),
            ],
        ),
    ]
