# Generated by Django 3.2.4 on 2021-10-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coso', '0002_auto_20211029_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coso',
            name='nganh_nghe',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
