# Generated by Django 3.2.4 on 2021-10-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coso', '0004_coso_thuoc_phu_luc_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coso',
            name='thuoc_phu_luc_2',
            field=models.BooleanField(default=False),
        ),
    ]
