# Generated by Django 3.2.4 on 2021-10-29 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coso', '0005_alter_coso_thuoc_phu_luc_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trang_thai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200)),
                ('mota', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='coso',
            name='trang_thai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coso.trang_thai'),
        ),
    ]
