# Generated by Django 3.2.4 on 2021-10-29 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coso', '0007_auto_20211029_1547'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diaban',
            new_name='Dia_ban',
        ),
        migrations.DeleteModel(
            name='Nganh_nghe',
        ),
    ]
