# Generated by Django 3.2.4 on 2021-10-31 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coso', '0008_auto_20211029_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Huan_luyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_in_school', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2)),
            ],
        ),
    ]
