# Generated by Django 3.2.4 on 2021-10-31 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coso', '0009_huan_luyen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huan_luyen',
            name='year_in_school',
            field=models.CharField(choices=[('FRESHMAN', 'Freshman'), ('SOPHOMORE', 'Sophomore'), ('JUNIOR', 'Junior'), ('SENIOR', 'Senior'), ('GRADUATE', 'Graduate')], default='FRESHMAN', max_length=20),
        ),
    ]
