# Generated by Django 3.2.4 on 2021-11-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coso', '0010_alter_huan_luyen_year_in_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huan_luyen',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='huan_luyen',
            name='co_so',
            field=models.ManyToManyField(blank=True, null=True, to='coso.Coso'),
        ),
        migrations.AddField(
            model_name='huan_luyen',
            name='trang_thai',
            field=models.IntegerField(choices=[(1, 'Tiếp nhận'), (2, 'Đã xây dựng kế hoạch'), (3, 'Kết thúc'), (4, 'Tạm ngưng'), (5, 'Hủy')], default=1, max_length=20),
        ),
    ]
