# Generated by Django 3.2.4 on 2021-11-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coso', '0011_auto_20211108_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='huan_luyen',
            name='loai',
            field=models.IntegerField(choices=[(1, 'Tiếp nhận'), (2, 'Đã xây dựng kế hoạch'), (3, 'Kết thúc'), (4, 'Tạm ngưng'), (5, 'Hủy')], default=1),
        ),
        migrations.AlterField(
            model_name='huan_luyen',
            name='trang_thai',
            field=models.IntegerField(choices=[(1, 'Tiếp nhận'), (2, 'Đã xây dựng kế hoạch'), (3, 'Kết thúc'), (4, 'Tạm ngưng'), (5, 'Hủy')], default=1),
        ),
    ]
