# Generated by Django 3.2.4 on 2021-11-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coso', '0012_auto_20211108_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huan_luyen',
            name='loai',
            field=models.IntegerField(choices=[(1, 'PCCC'), (2, 'CNCH')], default=1),
        ),
    ]
