# Generated by Django 3.2.4 on 2021-11-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coso', '0013_alter_huan_luyen_loai'),
    ]

    operations = [
        migrations.AddField(
            model_name='huan_luyen',
            name='ngay_cap_giay',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='huan_luyen',
            name='ngay_de_nghi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='huan_luyen',
            name='ngay_huan_luyen',
            field=models.DateField(blank=True, null=True),
        ),
    ]
